# 1. Veritaban\u0131 Ba\u011flant\u0131s\u0131
spring.datasource.url=jdbc:postgresql://localhost:5432/GazzeHaberSistemi
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. JPA (Veritaban\u0131 Y\u00f6netim) Ayarlar\u0131
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' modu: Java'da yeni bir \u015fey eklersen veritaban\u0131n\u0131 bozmadan g\u00fcnceller
spring.jpa.hibernate.ddl-auto=update
# Konsolda SQL sorgular\u0131n\u0131 g\u00f6rmek i\u00e7in (Hata ay\u0131klarken \u00e7ok i\u015fe yarar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true